# Generated by Django 5.2.7 on 2025-10-24 09:57

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BarbershopAppointment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("customer_name", models.CharField(max_length=100)),
                ("customer_phone", models.CharField(max_length=20)),
                (
                    "customer_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "service",
                    models.CharField(
                        choices=[
                            ("Haircut", "Haircut - ₹300"),
                            ("Beard Trim", "Beard Trim - ₹200"),
                            ("Hair + Beard", "Hair + Beard - ₹450"),
                            ("Shave", "Shave - ₹250"),
                            ("Hair Color", "Hair Color - ₹500"),
                        ],
                        max_length=50,
                    ),
                ),
                ("barber_name", models.CharField(max_length=100)),
                ("appointment_date", models.DateField()),
                ("appointment_time", models.TimeField()),
                ("duration_minutes", models.PositiveIntegerField(default=60)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("confirmed", "Confirmed"),
                            ("pending", "Pending"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                            ("no_show", "No Show"),
                        ],
                        default="confirmed",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "barbershop",
                    models.ForeignKey(
                        limit_choices_to={"role": "barbershop"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="barbershop_appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-appointment_date", "-appointment_time"],
            },
        ),
        migrations.CreateModel(
            name="BarbershopCustomer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Preferences, allergies, etc."
                    ),
                ),
                ("total_visits", models.PositiveIntegerField(default=0)),
                ("last_visit_date", models.DateField(blank=True, null=True)),
                (
                    "total_spent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "barbershop",
                    models.ForeignKey(
                        limit_choices_to={"role": "barbershop"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="barbershop_customers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_visit_date", "name"],
            },
        ),
        migrations.CreateModel(
            name="BarbershopInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Hair Products", "Hair Products"),
                            ("Shaving", "Shaving"),
                            ("Tools", "Tools"),
                            ("Cleaning", "Cleaning"),
                            ("Other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=0)),
                (
                    "min_stock",
                    models.PositiveIntegerField(
                        default=5, help_text="Minimum stock level for alerts"
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("supplier", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "barbershop",
                    models.ForeignKey(
                        limit_choices_to={"role": "barbershop"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="barbershop_inventory",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Barbershop Inventory",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="BarbershopSale",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("customer_name", models.CharField(max_length=100)),
                (
                    "service",
                    models.CharField(
                        choices=[
                            ("Haircut", "Haircut"),
                            ("Beard Trim", "Beard Trim"),
                            ("Hair + Beard", "Hair + Beard"),
                            ("Shave", "Shave"),
                            ("Hair Color", "Hair Color"),
                        ],
                        max_length=50,
                    ),
                ),
                ("barber_name", models.CharField(max_length=100)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("Cash", "Cash"),
                            ("UPI", "UPI"),
                            ("Card", "Card"),
                            ("Paytm", "Paytm"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("sale_date", models.DateField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appointment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sale",
                        to="barbershop_operations.barbershopappointment",
                    ),
                ),
                (
                    "barbershop",
                    models.ForeignKey(
                        limit_choices_to={"role": "barbershop"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="barbershop_sales",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-sale_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BarbershopStaff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Barber", "Barber"),
                            ("Senior Barber", "Senior Barber"),
                            ("Manager", "Manager"),
                            ("Receptionist", "Receptionist"),
                        ],
                        max_length=20,
                    ),
                ),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("schedule", models.TextField(help_text="Working hours and days")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Inactive", "Inactive"),
                            ("On Leave", "On Leave"),
                        ],
                        default="Active",
                        max_length=20,
                    ),
                ),
                (
                    "salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("join_date", models.DateField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "barbershop",
                    models.ForeignKey(
                        limit_choices_to={"role": "barbershop"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="barbershop_staff",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BarbershopActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("appointment_created", "Appointment Created"),
                            ("appointment_updated", "Appointment Updated"),
                            ("appointment_cancelled", "Appointment Cancelled"),
                            ("appointment_completed", "Appointment Completed"),
                            ("sale_recorded", "Sale Recorded"),
                            ("sale_updated", "Sale Updated"),
                            ("staff_added", "Staff Added"),
                            ("staff_updated", "Staff Updated"),
                            ("customer_added", "Customer Added"),
                            ("customer_updated", "Customer Updated"),
                            ("inventory_added", "Inventory Added"),
                            ("inventory_updated", "Inventory Updated"),
                            ("inventory_low_stock", "Low Stock Alert"),
                            ("login", "User Login"),
                            ("profile_updated", "Profile Updated"),
                            ("settings_changed", "Settings Changed"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "barbershop",
                    models.ForeignKey(
                        limit_choices_to={"role": "barbershop"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="barbershop_activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="barbershop_operations.barbershopappointment",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="barbershop_operations.barbershopcustomer",
                    ),
                ),
                (
                    "inventory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="barbershop_operations.barbershopinventory",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="barbershop_operations.barbershopsale",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="barbershop_operations.barbershopstaff",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BarbershopStaffAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("is_available", models.BooleanField(default=True)),
                ("notes", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability_overrides",
                        to="barbershop_operations.barbershopstaff",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "start_time"],
            },
        ),
        migrations.AddIndex(
            model_name="barbershopappointment",
            index=models.Index(
                fields=["barbershop", "appointment_date"],
                name="barbershop__barbers_ee71cc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="barbershopappointment",
            index=models.Index(
                fields=["barbershop", "status"], name="barbershop__barbers_24d479_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="barbershopappointment",
            index=models.Index(
                fields=["barber_name", "appointment_date"],
                name="barbershop__barber__61c931_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="barbershopcustomer",
            index=models.Index(
                fields=["barbershop", "phone"], name="barbershop__barbers_a81b30_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="barbershopcustomer",
            index=models.Index(
                fields=["barbershop", "last_visit_date"],
                name="barbershop__barbers_9cb6ca_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="barbershopcustomer",
            unique_together={("barbershop", "phone")},
        ),
        migrations.AddIndex(
            model_name="barbershopinventory",
            index=models.Index(
                fields=["barbershop", "category"], name="barbershop__barbers_f1899b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="barbershopinventory",
            index=models.Index(
                fields=["barbershop", "quantity"], name="barbershop__barbers_622c24_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="barbershopinventory",
            unique_together={("barbershop", "name")},
        ),
        migrations.AddIndex(
            model_name="barbershopsale",
            index=models.Index(
                fields=["barbershop", "sale_date"],
                name="barbershop__barbers_13d0ab_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="barbershopsale",
            index=models.Index(
                fields=["barbershop", "payment_method"],
                name="barbershop__barbers_6d7666_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="barbershopsale",
            index=models.Index(
                fields=["barber_name", "sale_date"],
                name="barbershop__barber__ad38e0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="barbershopstaff",
            index=models.Index(
                fields=["barbershop", "status"], name="barbershop__barbers_6109fb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="barbershopstaff",
            index=models.Index(
                fields=["barbershop", "role"], name="barbershop__barbers_ea1fd3_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="barbershopstaff",
            unique_together={("barbershop", "phone")},
        ),
        migrations.AddIndex(
            model_name="barbershopactivitylog",
            index=models.Index(
                fields=["barbershop", "action_type"],
                name="barbershop__barbers_c28085_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="barbershopactivitylog",
            index=models.Index(
                fields=["barbershop", "created_at"],
                name="barbershop__barbers_399764_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="barbershopstaffavailability",
            index=models.Index(
                fields=["staff", "date"], name="barbershop__staff_i_f5cacf_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="barbershopstaffavailability",
            unique_together={("staff", "date")},
        ),
    ]
