# Generated by Django 5.2.7 on 2025-10-31 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("barbershop_operations", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="barbershopstaffavailability",
            unique_together={("staff", "date", "start_time")},
        ),
        migrations.AddIndex(
            model_name="barbershopstaffavailability",
            index=models.Index(
                fields=["staff", "date", "start_time"],
                name="barbershop__staff_i_5dfdab_idx",
            ),
        ),
    ]
