# Generated by Django 5.2.7 on 2025-11-02 10:54

import barbershop_operations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "barbershop_operations",
            "0002_alter_barbershopstaffavailability_unique_together_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="barbershopsale",
            name="sale_date",
            field=models.DateField(
                default=barbershop_operations.models.get_current_date
            ),
        ),
        migrations.AlterField(
            model_name="barbershopstaff",
            name="join_date",
            field=models.DateField(
                default=barbershop_operations.models.get_current_date
            ),
        ),
    ]
