# Generated by Django 5.2.7 on 2025-11-02 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("barbershop_operations", "0003_alter_barbershopsale_sale_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="barbershopinventory",
            name="selling_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Selling price per unit",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="barbershopinventory",
            name="unit_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Cost price per unit",
                max_digits=10,
            ),
        ),
    ]
