# Generated by Django 5.2.7 on 2025-11-03 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("barbershop_operations", "0004_barbershopinventory_selling_price_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="barbershopactivitylog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("appointment_created", "Appointment Created"),
                    ("appointment_updated", "Appointment Updated"),
                    ("appointment_cancelled", "Appointment Cancelled"),
                    ("appointment_completed", "Appointment Completed"),
                    ("sale_recorded", "Sale Recorded"),
                    ("sale_updated", "Sale Updated"),
                    ("staff_added", "Staff Added"),
                    ("staff_updated", "Staff Updated"),
                    ("customer_added", "Customer Added"),
                    ("customer_updated", "Customer Updated"),
                    ("inventory_added", "Inventory Added"),
                    ("inventory_updated", "Inventory Updated"),
                    ("inventory_low_stock", "Low Stock Alert"),
                    ("service_added", "Service Added"),
                    ("service_updated", "Service Updated"),
                    ("service_deleted", "Service Deleted"),
                    ("login", "User Login"),
                    ("profile_updated", "Profile Updated"),
                    ("settings_changed", "Settings Changed"),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="BarbershopService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        default=60, help_text="Default duration in minutes"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "barbershop",
                    models.ForeignKey(
                        limit_choices_to={"role": "barbershop"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="barbershop_services",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["barbershop", "is_active"],
                        name="barbershop__barbers_086527_idx",
                    ),
                    models.Index(
                        fields=["barbershop", "name"],
                        name="barbershop__barbers_ed6544_idx",
                    ),
                ],
                "unique_together": {("barbershop", "name")},
            },
        ),
    ]
