# Generated by Django 5.2.7 on 2025-11-03 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "barbershop_operations",
            "0005_alter_barbershopactivitylog_action_type_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="barbershopservice",
            name="duration_minutes",
        ),
    ]
