# Generated by Django 5.2.7 on 2025-10-22 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="shop_logo",
            field=models.ImageField(blank=True, null=True, upload_to="shop_logos/"),
        ),
        migrations.AddField(
            model_name="user",
            name="shop_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="shop_owner_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("customer", "Customer"),
                    ("barber", "Barber"),
                    ("barbershop", "Barbershop"),
                    ("admin", "Admin"),
                    ("super_admin", "Super Admin"),
                ],
                default="customer",
                max_length=20,
            ),
        ),
    ]
