# Generated by Django 5.2.7 on 2025-10-24 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("service_update", "Service Update"),
                            ("appointment_added", "Appointment Added"),
                            ("payment_processed", "Payment Processed"),
                            ("profile_updated", "Profile Updated"),
                            ("status_changed", "Status Changed"),
                            ("subscription_changed", "Subscription Changed"),
                            ("staff_added", "Staff Added"),
                            ("hours_updated", "Hours Updated"),
                        ],
                        help_text="Type of activity performed",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Detailed description of the activity"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Amount associated with activity (for payments/revenue)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the activity occurred"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional activity data"
                    ),
                ),
                (
                    "barbershop",
                    models.ForeignKey(
                        help_text="The barbershop this activity belongs to",
                        limit_choices_to={"role": "barbershop"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity",
                "verbose_name_plural": "Activities",
                "db_table": "barbershop_admin_activity",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["barbershop", "-timestamp"],
                        name="barbershop__barbers_04dab6_idx",
                    ),
                    models.Index(
                        fields=["action_type", "-timestamp"],
                        name="barbershop__action__23ff9a_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AdminReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("monthly_summary", "Monthly Summary"),
                            ("barbershop_performance", "Barbershop Performance"),
                            ("revenue_analysis", "Revenue Analysis"),
                            ("appointment_trends", "Appointment Trends"),
                        ],
                        help_text="Type of report generated",
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(help_text="Report title", max_length=255)),
                ("data", models.JSONField(help_text="Report data in JSON format")),
                (
                    "period_start",
                    models.DateField(help_text="Start date for report period"),
                ),
                (
                    "period_end",
                    models.DateField(help_text="End date for report period"),
                ),
                (
                    "generated_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the report was generated"
                    ),
                ),
                (
                    "admin_user",
                    models.ForeignKey(
                        help_text="Admin who generated this report",
                        limit_choices_to={"role": "admin"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Admin Report",
                "verbose_name_plural": "Admin Reports",
                "db_table": "barbershop_admin_report",
                "ordering": ["-generated_at"],
                "indexes": [
                    models.Index(
                        fields=["admin_user", "-generated_at"],
                        name="barbershop__admin_u_5c8689_idx",
                    ),
                    models.Index(
                        fields=["report_type", "-generated_at"],
                        name="barbershop__report__002971_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(help_text="Name of the customer", max_length=255),
                ),
                (
                    "customer_email",
                    models.EmailField(
                        blank=True,
                        help_text="Customer email address",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "customer_phone",
                    models.CharField(
                        blank=True,
                        help_text="Customer phone number",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "service",
                    models.CharField(help_text="Service(s) requested", max_length=255),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total appointment cost",
                        max_digits=10,
                    ),
                ),
                (
                    "appointment_date",
                    models.DateTimeField(
                        help_text="Scheduled appointment date and time"
                    ),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(
                        default=60, help_text="Appointment duration in minutes"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("confirmed", "Confirmed"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                        ],
                        default="scheduled",
                        help_text="Current appointment status",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about the appointment",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the appointment was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When the appointment was last updated"
                    ),
                ),
                (
                    "barbershop",
                    models.ForeignKey(
                        help_text="The barbershop where appointment is scheduled",
                        limit_choices_to={"role": "barbershop"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Appointment",
                "verbose_name_plural": "Appointments",
                "db_table": "barbershop_admin_appointment",
                "ordering": ["-appointment_date"],
                "indexes": [
                    models.Index(
                        fields=["barbershop", "-appointment_date"],
                        name="barbershop__barbers_dd5a3f_idx",
                    ),
                    models.Index(
                        fields=["status", "-appointment_date"],
                        name="barbershop__status_a6ec19_idx",
                    ),
                    models.Index(
                        fields=["appointment_date"],
                        name="barbershop__appoint_017df7_idx",
                    ),
                ],
            },
        ),
    ]
