# Generated by Django 5.2.7 on 2025-11-01 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("barbershop_admin", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("service_update", "Service Update"),
                    ("appointment_added", "Appointment Added"),
                    ("payment_processed", "Payment Processed"),
                    ("profile_updated", "Profile Updated"),
                    ("status_changed", "Status Changed"),
                    ("subscription_changed", "Subscription Changed"),
                    ("staff_added", "Staff Added"),
                    ("hours_updated", "Hours Updated"),
                    ("transfer_out", "Barbershop Transferred Out"),
                    ("transfer_in", "Barbershop Transferred In"),
                ],
                help_text="Type of activity performed",
                max_length=50,
            ),
        ),
    ]
